### ISSUE TITLE
input_shape-caused-error

### ISSUE THREAD

**Issue by hyoonsoo** [cchoquette/membership-inference#3]
I'm doing an experiment with texas data.
And in utils.py,  input_dim = 6168 in original code.
I recieved error:

'''
Traceback (most recent call last):
  File "training.py", line 307, in <module>
    target_model = model(input_dim, args.model_depth, regularization, args.reg_constant, n_classes)
  File "/home/yoon/membership-inference/models.py", line 18, in make_conv
    if len(input_shape) == 2:
TypeError: object of type 'int' has no len()

'''
I think input_shape  should be a tuple.
Or I think the versions are different

I'm working in
tensorflow-gpu 1.15.0
tensorflow-privacy 0.5.0
keras 2.6.0

Can you give me 'requirement' information? :-D
thank you.

**Comment by cchoquette** [comment]
I believe you are calling make_conv with the wrong dataset. Try using one of 'cifar10', 'cifar100' or 'mnist'. Alternatively, if you want to use one of the tabular datasets, you should use 'make_fc'

Does that fix the problem?
